title = "ColeApp gitleaks config"

[extend]
# Extend the base configuration with the default gitleaks config
useDefault = true

[allowlist]
description = "Global allow list"
paths = [
    '''^\.gitleaks\.toml$''',
    '''\.env\.example$''',
    '''\.env\.template$''',
    '''/tests?/''',
    '''/__tests__/''',
    '''/node_modules/''',
    '''\.next/''',
    '''/dist/''',
    '''/build/'''
]

# Allow common test strings
regexes = [
    '''EXAMPLE''',
    '''SAMPLE''',
    '''YOUR_.*_HERE''',
    '''<your-.*>''',
    '''placeholder''',
    '''test''',
    '''demo''',
    '''dummy''',
    '''fake'''
]